apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: webpage
  replicas: 3
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpagepod
        image: bhavya16/swe645assignment2:latest
        ports:
        - containerPort: 80
